import { CartItemData } from './types';

export const cartItemData: CartItemData[] = [
  {
    id: 1,
    name: 'ct1621 [울50%] (컬러추가/폭닥포근/누빔안감) 아도르 울 부클 싱글 하프 코트',
    color: 'red',
    size: 'L',
    amount: 1,
    price: 15000,
    image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Coat+1',
  },
  {
    id: 2,
    name: 'ct1621 [울50%] (컬러추가/폭닥포근/누빔안감) 아도르 울 부클 싱글 하프 코트',
    color: 'red',
    size: 'L',
    amount: 2,
    price: 115000,
    image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=Coat+2',
  },
  {
    id: 3,
    name: '골프공',
    color: 'red',
    size: 'M',
    amount: 3,
    price: 20000,
    image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Golf+Ball',
  },
  {
    id: 4,
    name: '골프 파우치',
    color: 'blue',
    size: 'S',
    amount: 4,
    price: 50000,
    image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Golf+Pouch',
  },
  {
    id: 5,
    name: '골프공',
    color: 'red',
    size: 'M',
    amount: 3,
    price: 20000,
    image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Golf+Ball',
  },
  {
    id: 6,
    name: '골프 파우치',
    color: 'blue',
    size: 'S',
    amount: 4,
    price: 50000,
    image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Golf+Pouch',
  },
  {
    id: 7,
    name: '골프공',
    color: 'red',
    size: 'M',
    amount: 3,
    price: 20000,
    image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Golf+Ball',
  },
  {
    id: 8,
    name: '골프 파우치',
    color: 'blue',
    size: 'S',
    amount: 4,
    price: 50000,
    image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Golf+Pouch',
  },
];
